service: crud-app
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  stage: dev
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: '*'

custom:
  tableName: todo

plugins:
  - serverless-plugin-typescript

functions:
  getTodos:
    handler: endpoints/getTodos.handler
    events:
      - http:
          path: todos
          method: get
          cors: true
  getTodo:
    handler: endpoints/getTodo.handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
