service: crud-app
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript

